name: telegram_todo_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  firebase_core: 3.9.0
  firebase_database: 11.2.0
  televerse: ^2.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

